{% set name = "pyglet" %}
{% set version = "1.4.0" %}
{% set sha256 = "c2d0aed2b33b03288a032ed0cb6c19c0088833836194aebdb043782d426beccc" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    number: 0
    script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - freetype
    - future

test:
  requires:
    - libglu  # [linux]
  files:
    - run_tests.py
  commands:
    - python run_tests.py  # [not linux]
    - xvfb-run --server-args=":99 -screen 0 1024x768x24 -ac +extension GLX -noreset" python run_tests.py  # [linux]

about:
  home: https://pyglet.readthedocs.io/en/pyglet-1.3-maintenance/
  license: BSD-3-Clause
  license_family: BSD
  summary: 'Cross-platform windowing and multimedia library'

extra:
  recipe-maintainers:
    - mwcraig
    - jakirkham
    - r1chardj0n3s
    - silvester747
    - bitcraft
