{% set name = "pyglet" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b00570e7cdf6971af8953b6ece50d83d13272afa5d1f1197c58c0f478dd17743

build:
  number: 5000
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - freetype
    - future
    - ffmpeg

test:
  # We moved all "import ..." tests to `run_tests.py` because on Linux, we
  # need to run the tests through xvfb-run as some of them require a
  # (virtual) display. On Windows and macOS, on the other hand, we can run the
  # test script directly.
  requires:
    - libglu  # [linux]
  files:
    - run_tests.py
  commands:
    - python run_tests.py  # [not linux]
    - xvfb-run --server-args=":99 -screen 0 1024x768x24 -ac +extension GLX -noreset" python run_tests.py  # [linux]

about:
  home: http://pyglet.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Cross-platform windowing and multimedia library'
  dev_url: https://github.com/pyglet/pyglet

extra:
  recipe-maintainers:
    - mwcraig
    - jakirkham
    - bitcraft
    - hoechenberger
