travis:
  secure:
    BINSTAR_TOKEN: OZ3MZcOBtEW2RoLWUmoyCXOE2YuVPE2CUHPnck06mRZn0kKWKDuw1Jc1MCid3qkRs3VhglatgTXevQC9l7yw3ownZmA9oHNKshJwbzmuV1nZgSyi0JkDqcx7hezmlFKpI+CmW2qVhBz82B64T+0xwMqbeFuFKXOihQWGyeuQ7A6emLlO57HHb5OrB6J9uIYgUyXcCnYoPoavRL8ynsNnJeTCVYbkLsuIv2G+7Z8YASltz143Q+zWnGNaEiKtFlkncsNgQIWrwVDoFIQWrhPdNbRph4fLVRarwniYGoHtirEjeN2CmYLncenzl+ciZ4OUapyLl9UKMGIG5fi11ywFpvR/5ljCrBzyoSav6ufRhPXFMR1oC2IMKsyq/UtFiSVt1sXataHD0p/8WU1zkzAehyvvpTRjlFt/oiVNrGicYG7yjaLFlus9mMpMqJkEqW8PANY+NYFGMf6/nsy6nsfaddEAbk4UItULfey/e2Hdgs+ZoWEJl0h1sYA86BbGDoEdY3YXja1sQIDvCeeP2upm1rvrDimc1jz6XGTbSXyxPAoZgFqd0HPMLESBBQ219lB8U3F29/yMHiQZzcGcEZLpdep2wDjwRmJq8bHXjSJlVjKXYz8JGSk4qbkWRbpwjHFbPVoJHG3TRoSG9XVm0a6p6E9uvBE6zQO8newNrYiKBI4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
